# Generated by Django 5.1.4 on 2026-06-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peetha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('acharya', models.CharField(help_text='Founding Acharya name', max_length=200)),
                ('simhasana', models.CharField(help_text='Name of the Simhasana (throne)', max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('current_swamiji', models.CharField(blank=True, max_length=400)),
                ('associated_linga', models.CharField(max_length=200)),
                ('color', models.CharField(help_text='CSS color for this Peetha', max_length=50)),
                ('description', models.TextField(help_text='Brief summary')),
                ('history', models.TextField(help_text='Detailed history and origin story')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
