# Generated by Django 5.1.4 on 2026-06-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peetha',
            name='acharya_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='acharya_kn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='acharya_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='associated_linga_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='associated_linga_kn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='associated_linga_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='current_swamiji_hi',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='peetha',
            name='current_swamiji_kn',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='peetha',
            name='current_swamiji_mr',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='peetha',
            name='description_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='description_kn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='description_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='history_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='history_kn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='history_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='location_hi',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='peetha',
            name='location_kn',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='peetha',
            name='location_mr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='peetha',
            name='name_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='name_kn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='name_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='simhasana_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='simhasana_kn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='simhasana_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
