# Generated by Django 5.1.4 on 2026-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0002_peetha_acharya_hi_peetha_acharya_kn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peetha',
            name='associated_linga_map_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for the associated Linga location'),
        ),
    ]
