# Generated by Django 5.1.4 on 2026-06-06 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0003_peetha_associated_linga_map_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeethaHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peetha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlers', to='peethas.peetha')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handler_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeethaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='peetha_media/photos/')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube Video URL', null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title_kn', models.CharField(blank=True, max_length=200)),
                ('description_kn', models.TextField(blank=True)),
                ('title_mr', models.CharField(blank=True, max_length=200)),
                ('description_mr', models.TextField(blank=True)),
                ('title_hi', models.CharField(blank=True, max_length=200)),
                ('description_hi', models.TextField(blank=True)),
                ('peetha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='peethas.peetha')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title_kn', models.CharField(blank=True, max_length=200)),
                ('location_kn', models.CharField(blank=True, max_length=300)),
                ('description_kn', models.TextField(blank=True)),
                ('title_mr', models.CharField(blank=True, max_length=200)),
                ('location_mr', models.CharField(blank=True, max_length=300)),
                ('description_mr', models.TextField(blank=True)),
                ('title_hi', models.CharField(blank=True, max_length=200)),
                ('location_hi', models.CharField(blank=True, max_length=300)),
                ('description_hi', models.TextField(blank=True)),
                ('peetha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to='peethas.peetha')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
