# Generated by Django 5.1.4 on 2026-06-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0004_peethahandler_peethamedia_travelplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='peetha',
            name='contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='peetha',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='peetha',
            name='swamiji_bio',
            field=models.TextField(blank=True, help_text='Biography of the current Jagathguru'),
        ),
        migrations.AddField(
            model_name='peetha',
            name='swamiji_photo',
            field=models.ImageField(blank=True, help_text='Photo of the current Jagathguru', null=True, upload_to='peetha_media/swamiji/'),
        ),
    ]
