# Generated by Django 5.1.4 on 2026-06-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0005_peetha_contact_address_peetha_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeethaPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_key_id', models.CharField(help_text='Razorpay Key ID for this Peetha', max_length=100)),
                ('razorpay_key_secret', models.CharField(help_text='Razorpay Key Secret for this Peetha', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/Disable online payments for this Peetha')),
                ('peetha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='peethas.peetha')),
            ],
        ),
        migrations.CreateModel(
            name='Pooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Rupees', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name_kn', models.CharField(blank=True, max_length=200)),
                ('description_kn', models.TextField(blank=True)),
                ('name_mr', models.CharField(blank=True, max_length=200)),
                ('description_mr', models.TextField(blank=True)),
                ('name_hi', models.CharField(blank=True, max_length=200)),
                ('description_hi', models.TextField(blank=True)),
                ('peetha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poojas', to='peethas.peetha')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PoojaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devotee_name', models.CharField(max_length=200)),
                ('devotee_phone', models.CharField(max_length=20)),
                ('devotee_email', models.EmailField(blank=True, max_length=254)),
                ('gotra', models.CharField(blank=True, max_length=100)),
                ('nakshatra', models.CharField(blank=True, max_length=100)),
                ('date_of_pooja', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pooja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='peethas.pooja')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
