# Generated by Django 5.1.4 on 2026-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0007_poojabooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='peetha',
            name='acharya_ml',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='acharya_ta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='acharya_te',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='associated_linga_ml',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='associated_linga_ta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='associated_linga_te',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='current_swamiji_ml',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='peetha',
            name='current_swamiji_ta',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='peetha',
            name='current_swamiji_te',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='peetha',
            name='description_ml',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='description_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='description_te',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='history_ml',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='history_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='history_te',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peetha',
            name='location_ml',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='peetha',
            name='location_ta',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='peetha',
            name='location_te',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='peetha',
            name='name_ml',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='name_ta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='name_te',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='simhasana_ml',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='simhasana_ta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peetha',
            name='simhasana_te',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peethamedia',
            name='description_ml',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peethamedia',
            name='description_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peethamedia',
            name='description_te',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peethamedia',
            name='title_ml',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peethamedia',
            name='title_ta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peethamedia',
            name='title_te',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pooja',
            name='description_ml',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pooja',
            name='description_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pooja',
            name='description_te',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pooja',
            name='name_ml',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pooja',
            name='name_ta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pooja',
            name='name_te',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='description_ml',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='description_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='description_te',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='location_ml',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='location_ta',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='location_te',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='title_ml',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='title_ta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='title_te',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
