# Generated by Django 5.1.15 on 2026-06-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0009_featureflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='peetha',
            name='live_youtube_url',
            field=models.URLField(blank=True, help_text='YouTube Live stream URL (leave blank if not active)', null=True),
        ),
    ]
