# Generated by Django 5.1.15 on 2026-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0010_peetha_live_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='peetha',
            name='live_youtube_title',
            field=models.CharField(blank=True, help_text="Custom title for the live stream (defaults to 'Swamiji Divine Live Stream' if blank)", max_length=200, null=True),
        ),
    ]
