# Generated by Django 5.1.15 on 2026-06-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0011_peetha_live_youtube_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja',
            name='category',
            field=models.CharField(choices=[('daily', 'Daily Seva'), ('special', 'Special Pooja'), ('homa', 'Homa & Havan'), ('utsava', 'Utsava / Festival Seva')], default='special', max_length=50),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='family_members',
            field=models.TextField(blank=True, help_text='Names of family members to include in sankalpa'),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='rashi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
