# Generated by Django 5.1.15 on 2026-06-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0012_pooja_category_poojabooking_family_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja',
            name='available_days',
            field=models.CharField(default='all', help_text="Comma-separated weekdays or 'all'", max_length=200),
        ),
        migrations.AddField(
            model_name='pooja',
            name='total_slots',
            field=models.PositiveIntegerField(default=10, help_text='Total available slots per day'),
        ),
    ]
