# Generated by Django 5.1.15 on 2026-06-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0015_userprofile_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('rooms_per_floor', models.PositiveIntegerField(default=5)),
                ('ac_floors_count', models.PositiveIntegerField(default=0, help_text='Number of floors starting from ground (floor 0) that have AC rooms. Other floors will have ordinary rooms.')),
                ('ac_room_price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('ordinary_room_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('peetha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='peethas.peetha')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.PositiveIntegerField(default=0)),
                ('room_type', models.CharField(choices=[('AC', 'AC Room'), ('Ordinary', 'Ordinary Room')], default='Ordinary', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='peethas.building')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('AC', 'AC Room'), ('Ordinary', 'Ordinary Room')], default='Ordinary', max_length=20)),
                ('devotee_name', models.CharField(max_length=200)),
                ('devotee_phone', models.CharField(max_length=20)),
                ('devotee_email', models.EmailField(blank=True, max_length=254)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('peetha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_bookings', to='peethas.peetha')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='peethas.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
