# Generated by Django 5.1.15 on 2026-06-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0016_building_room_accommodationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='ac_room_numbers',
            field=models.TextField(blank=True, default='', help_text="Comma-separated list of specific room numbers that should be AC (e.g. 'G1, G2, 101'). If specified, it overrides the AC floors count."),
        ),
        migrations.AddField(
            model_name='building',
            name='has_hot_water',
            field=models.BooleanField(default=False, help_text='Is hot water available in this building?'),
        ),
        migrations.AddField(
            model_name='building',
            name='hot_water_timings',
            field=models.CharField(blank=True, default='', help_text="Timings for hot water (e.g. '6:00 AM - 9:00 AM')", max_length=100),
        ),
    ]
