# Generated by Django 5.1.15 on 2026-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0017_building_ac_room_numbers_building_has_hot_water_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('heritage_intro', 'Heritage Intro'), ('veerashaiva_intro', 'Veerashaiva Intro'), ('veerashaiva_body', 'Veerashaiva Body'), ('veerashaiva_teachings', 'Veerashaiva Teachings')], max_length=30)),
                ('language', models.CharField(max_length=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Dynamic Paragraph',
                'verbose_name_plural': 'Dynamic Paragraphs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DynamicContentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('heritage', 'Heritage'), ('veerashaiva', 'Veerashaiva')], max_length=30)),
                ('language', models.CharField(max_length=5)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('conclusion', models.TextField(blank=True)),
                ('shloka_verse', models.TextField(blank=True)),
                ('shloka_translation', models.TextField(blank=True)),
                ('shloka_reference', models.CharField(blank=True, max_length=300)),
                ('siddhanta_intro', models.TextField(blank=True)),
                ('siddhanta_verse', models.TextField(blank=True)),
                ('siddhanta_translation_label', models.CharField(blank=True, max_length=100)),
                ('siddhanta_translation', models.TextField(blank=True)),
                ('teachings_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dynamic Content Meta',
                'verbose_name_plural': 'Dynamic Content Metas',
                'unique_together': {('section', 'language')},
            },
        ),
    ]
