# Generated by Django 5.1.15 on 2026-07-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0018_dynamicparagraph_dynamiccontentmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='peetha',
            name='mutt_photo',
            field=models.ImageField(blank=True, help_text='Photo of the Mutt/monastery', null=True, upload_to='peetha_media/mutts/'),
        ),
    ]
