# Generated by Django 5.1.15 on 2026-07-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0019_peetha_mutt_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='peetha',
            name='advance_booking_window',
            field=models.IntegerField(choices=[(0, 'Unlimited (Any future date)'), (30, '1 Month (30 days)'), (90, '3 Months (90 days)'), (180, '6 Months (180 days)')], default=0, help_text='Restrict how far in advance devotees can book poojas and accommodations.'),
        ),
    ]
