# Generated by Django 5.1.15 on 2026-07-15 10:23

from django.db import migrations

def seed_data(apps, schema_editor):
    Peetha = apps.get_model('peethas', 'Peetha')
    Pooja = apps.get_model('peethas', 'Pooja')
    Building = apps.get_model('peethas', 'Building')
    Room = apps.get_model('peethas', 'Room')

    # Try to get Rambhapuri, or just the first peetha
    peetha = Peetha.objects.filter(slug='rambhapuri').first()
    if not peetha:
        peetha = Peetha.objects.first()
    
    if not peetha:
        return # No peethas to attach to
        
    # Poojas
    poojas_data = [
        {'name': 'Rudrabhisheka', 'description': 'Sacred bathing of Shiva Linga with Rudra Mantras.', 'price': 500, 'category': 'special'},
        {'name': 'Kumkuma Archana', 'description': 'Offering of kumkuma with chanting of Lalitha Sahasranama.', 'price': 300, 'category': 'daily'},
        {'name': 'Panchamruta Abhisheka', 'description': 'Bathing of the deity with five sacred items.', 'price': 1000, 'category': 'special'},
    ]
    
    for pd in poojas_data:
        Pooja.objects.get_or_create(
            peetha=peetha,
            name=pd['name'],
            defaults={
                'description': pd['description'],
                'price': pd['price'],
                'category': pd['category'],
                'is_active': True,
                'total_slots': 10,
                'available_days': 'all',
            }
        )
        
    # Accommodation - Building
    building, created = Building.objects.get_or_create(
        peetha=peetha,
        name='Yatri Nivas',
        defaults={
            'description': 'Comfortable stay for devotees with modern amenities.',
            'total_floors': 2,
            'rooms_per_floor': 10,
            'ac_floors_count': 1,
            'ac_room_price': 1000,
            'ordinary_room_price': 500,
            'has_hot_water': True,
            'hot_water_timings': '6:00 AM - 9:00 AM',
            'is_active': True,
        }
    )
    
    # Generate rooms manually for the migration
    if created:
        for floor in range(building.total_floors):
            for room_idx in range(1, building.rooms_per_floor + 1):
                if floor == 0:
                    room_number = f"G{room_idx}"
                else:
                    room_number = f"{floor}{room_idx:02d}"
                    
                room_type = 'AC' if floor < building.ac_floors_count else 'Ordinary'
                price = building.ac_room_price if room_type == 'AC' else building.ordinary_room_price
                
                Room.objects.get_or_create(
                    building=building,
                    room_number=room_number,
                    defaults={
                        'floor': floor,
                        'room_type': room_type,
                        'price_per_night': price,
                        'is_active': True
                    }
                )

def revert_seed(apps, schema_editor):
    pass 

class Migration(migrations.Migration):

    dependencies = [
        ('peethas', '0020_peetha_advance_booking_window'),
    ]

    operations = [
        migrations.RunPython(seed_data, revert_seed),
    ]
